services:
  front:
    build: ./front
    container_name: ng-frontend
    volumes:
      - front-dist:/app/dist
    depends_on:
      - "back"
  back:
    build: ./back
    container_name: back-api
    ports:
      - "3000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - front-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back

volumes:
  postgres-data:
  front-dist:
