services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: ng-frontend
    ports:
      - "4200"
    volumes:
      - "./front:/app"
      - "/app/node_modules"
    command: ["npm", "start"]
    depends_on:
      - back
  back:
    build: ./back
    volumes:
      - "./back:/app"
    ports:
      - "3000"
    environment:
      NODE_ENV: development
    command: ["npm", "start"]
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back

volumes:
  postgres-data:
