services:
  app:
    build: .
    container_name: node-demo
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  front:
    build:
      context: ../front
    container_name: ng-frontend
    ports:
      - "4200:80"
    depends_on:
      - "app"


volumes:
  postgres-data:
